# Generated by Django 6.0.3 on 2026-03-08 17:16

import apps.documents.models
import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.user_document_path, validators=[apps.utils.validators.validate_document_file]),
        ),
    ]
