# Generated by Django 6.0.3 on 2026-03-08 17:16

import apps.users.models
import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.user_avatar_path, validators=[apps.utils.validators.validate_secure_image]),
        ),
    ]
